Q1(l_okey,l_linenumber,l_shipmode) :-
lineitem(l_okey,x8,x9,l_linenumber,x11,x12,x13,x14,x15,x16,l_shipdate,l_commitdate,l_receiptdate,x17,l_shipmode,x18),
l_commitdate < l_receiptdate,
l_shipdate < l_commitdate,
l_receiptdate >= '1994-01-01',
l_receiptdate < '1995-01-01' .

Q2(l_okey,l_linenumber,l_shipmode) :-
  Q1(l_okey,l_linenumber,l_shipmode) .

Q(l_shipmode) :-
  orders(o_okey,x1,x2,x3,x4,o_orderpriority,x5,x6,x7),
  Q2(o_okey,l_linenumber,l_shipmode) .
